// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"encoding/json"
)

type Order struct {
	OrderUid  string          `json:"order_uid"`
	OrderJson json.RawMessage `json:"order_json"`
}
